name: real_image

image_shape: [3, 240, 320]
dataset_path: data/pusht_real/real_pusht_20230105

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    camera_0: # global camera on the righ above
      shape: ${task.image_shape}
      type: rgb
    camera_1: # camera on the Right jaw
      shape: ${task.image_shape}
      type: rgb
    camera_2: # camera on the Left jaw
      shape: ${task.image_shape}
      type: rgb
    # camera_3: # camera attached to wall
    #   shape: ${task.image_shape}
    #   type: rgb
    # camera_4: # globa on the very top
    #   shape: ${task.image_shape}
    #   type: rgb
    robot_eef_pose:
      shape: [6] # modified 
      type: low_dim
    left_jaw: # added
      shape: [1] # added
      type: low_dim # added
    right_jaw: # added
      shape: [1] # added
      type: low_dim # added
  action: 
    shape: [8] # modified

    

env_runner:
  _target_: diffusion_policy.env_runner.real_pusht_image_runner.RealPushTImageRunner

dataset:
  _target_: diffusion_policy.dataset.real_pusht_image_dataset.RealPushTImageDataset
  shape_meta: *shape_meta
  dataset_path: ${task.dataset_path}
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${n_action_steps}-1'}
  n_obs_steps: ${dataset_obs_steps}
  n_latency_steps: ${n_latency_steps}
  use_cache: True
  seed: 42
  val_ratio: 0.00
  max_train_episodes: null
  delta_action: False

